name: flux_sliders
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pip:
      - torch==2.4.1 --index-url https://download.pytorch.org/whl/cu124
      - torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cu124
      - torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu124
      - diffusers==0.30.2
      - transformers==4.47.1
      - omegaconf==2.3.0
      - safetensors==0.5.0
      - filelock
      - accelerate
      - protobuf
      - sentencepiece
